### ISSUE TITLE
enable NFS over RDMA(--with-nfsrdma) by default

### ISSUE THREAD

**Issue by cyclinder** [Mellanox/ofed-docker#39]
There are all the default install parameters. 

https://github.com/Mellanox/ofed-docker/blob/4268a4823bf65982b6045e920f2a2f01f9bd7bc7/rhel/entrypoint.sh#L140

If I want to enable NFS over RDMA(--with-nfsrdma), what me to do?  We can write a new ENV like "MLNXOFEDINSTALL_ARGS" to https://github.com/Mellanox/ofed-docker/blob/master/deployment/ofed-driver-pod.yaml, and pass it to https://github.com/Mellanox/ofed-docker/blob/master/rhel/entrypoint.sh. 

For example:

```
apiVersion: v1
kind: Pod
metadata:
  name: ofed-driver
  labels:
    app: ofed-driver
spec:
  hostNetwork: true
  ENV:
  - name: MLNXOFEDINSTALL_ARGS
    value: "--with-nfsrdma --with-nvmf"
  containers:
    - name: ofed-driver
      image: ofed_container
      imagePullPolicy: Never
      securityContext:
        privileged: true
      volumeMounts:
        - name: run-mofed
          mountPath: /run/mellanox/drivers
          mountPropagation: Bidirectional
        - name: etc-network
          mountPath: /etc/network
        - name: host-etc
          mountPath: /host/etc
        - name: host-udev
          mountPath: /host/lib/udev
```

How do you think? If you guys think so, I'm willing to do this.
